//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetergentsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.SheetType = new HashSet<SheetType>();
        }
    
        public int productID { get; set; }
        public string EAN { get; set; }
        public int sheetTypeID { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public int categoryID { get; set; }
        public int articleNumber { get; set; }
        public int vendorID { get; set; }
        public int countryID { get; set; }
        public int storeID { get; set; }
        public long articleID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SheetType> SheetType { get; set; }
        public virtual VendorSet Vendor { get; set; }
        public virtual Country Country { get; set; }
        public virtual StoreAPI Store { get; set; }
        public virtual articleDetailsAPI articleDetails { get; set; }
    }
}
