//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DetergentsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [ScaffoldColumn(false)]
        public int ProductID { get; set; }
        public int EAN { get; set; }
        public string Title { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public Nullable<int> FileID { get; set; }

    }
}
