//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Kendo.Mvc.UI;

namespace DetergentsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Product
    {
        [Key][ScaffoldColumn(false)]
        public int ProductID { get; set; }
        public int EAN { get; set; }
        public int articleNR { get; set; }
        public string Title { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        
        public Nullable<int> CategoryID { get; set; }
        public virtual Category Category { get; set; }
        
        
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = false)]
        [Display(Name = "Valid From")]
        public System.DateTime validFrom { get; set; }
    
        
    }
}
